# Generated by Django 6.0.5 on 2026-05-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_city', models.CharField(max_length=255)),
                ('to_city', models.CharField(max_length=255)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('driver_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_loads', to='currencies.currency')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('driver_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_loads', to='currencies.currency')),
            ],
        ),
    ]
