# Generated by Django 6.0.5 on 2026-05-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
    ]
