# Generated by Django 6.0.5 on 2026-05-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('currencies', '0001_initial'),
        ('finance', '0001_initial'),
        ('loads', '0002_load_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brokers.broker'),
        ),
        migrations.AddField(
            model_name='load',
            name='broker_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_currency_loads', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='load',
            name='broker_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='load',
            name='broker_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_payment_methods', to='finance.paymentmethod'),
        ),
    ]
