# Generated by Django 6.0.5 on 2026-05-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('dispatchers', '0001_initial'),
        ('finance', '0001_initial'),
        ('loads', '0003_load_broker_load_broker_currency_load_broker_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatchers.dispatcher'),
        ),
        migrations.AddField(
            model_name='load',
            name='dispatcher_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher_currency_loads', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='load',
            name='dispatcher_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='load',
            name='dispatcher_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher_payment_methods', to='finance.paymentmethod'),
        ),
    ]
